// icon_map.js
// Centralized mapping for item icons to handle different casings and special names

const ICON_MAP = {
            "Dirt": "dirt", "Stone": "stone", "Sand": "sand", "IronOre": "ironore", "Coal": "coal", "CopperOre": "copperore",
            "GoldOre": "goldore", "Grass": "dirtgrass", "WaterBucket": "water", "LavaBucket": "lava", "SilverOre": "silverore",
            "DiamondOre": "diamond", "Ice": "ice", "Gel": "gel", "Arrow": "arrow", "CopperIngot": "CopperIngot",
            "IronIngot": "IronIngot", "SilverIngot": "SilverIngot", "GoldIngot": "GoldIngot",
            "Diamond": "diamond", "Ruby": "ruby", "Emerald": "emerald", "Sapphire": "sapphire", "Topaz": "topaz",
            "Aquamarine": "aquamarine", "SpessartiteGarnet": "spessartiteGarnet", "Amethyst": "amethyst",
            "Morganite": "morganite", "Onyx": "onyx", "Moss": "moss", "Snow": "snow", "Glass": "glass",
            "OakLeaves": "oakleaves", "MangroveLeaves": "mangroveleaves", "PineLeaves": "pineleaves",
            "CherryBlossomLeaves": "cherryblossomleaves", "BeechLeaves": "beechleaves",
            "OnyxBrick": "onyxbrick", "MorganiteBrick": "morganitebrick", "AmethystBrick": "amethystbrick",
            "SpessartiteBrick": "spessartitegarnetbrick", "AquamarineBrick": "aquamarinebrick",
            "TopazBrick": "topazbrick", "SapphireBrick": "sapphirebrick", "EmeraldBrick": "emeraldbrick",
            "RubyBrick": "rubybrick", "DiamondBrick": "diamondbrick", "Lilypad": "lilypad",
            "MorganiteLightstone": "morganitelightstone", "AmethystLightstone": "amethystlightstone",
            "SpessartiteLightstone": "spessartitegarnetlightstone", "AquamarineLightstone": "aquamarinelightstone",
            "TopazLightstone": "topazlightstone", "SapphireLightstone": "sapphirelightstone",
            "EmeraldLightstone": "emeraldlightstone", "RubyLightstone": "rubylightstone",
            "TinOre": "tinore", "LeadOre": "leadore", "Amberstone": "amberstone", "TungstenOre": "tungstenore",
            "PlatinumOre": "platinumore", "CobaltOre": "cobaltore", "MythrilOre": "mythrilore",
            "Cobweb": "cobweb", "TinIngot": "TinIngot", "LeadIngot": "LeadIngot", "TungstenIngot": "TungstenIngot",
            "PlatinumIngot": "PlatinumIngot", "AmberstoneIngot": "AmberstoneIngot", "Strings": "strings",
            "BlueRose": "bluerose", "Flowstone": "flowstone", "Cactus": "cactus", "Rail": "rail",
            "SlimelingCore": "SlimelingCore", "DemonMushroom": "DemonMushroom", "Mushroom": "Mushroom",
            "BoneFragment": "bone", "GoldenFeather": "feather", "Log": "Log",
            "RingOfSwiftness": "ringofswiftness",
            "BandOfRegeneration": "BandOfRegeneration", "WoodenShield": "WoodenShield",
            "ReinforcedWoodShield": "ReinforcedWoodShield", "CopperPlatedGuard": "CopperPlatedGuard",
            "GladiatorsRoundshield": "GladiatorsRoundshield", "IronHeaterShield": "IronHeaterShield",
            "GoldLayeredBulwark": "GoldLayeredBulwark", "CobaltStuddedShield": "CobaltStuddedShield",
            "RoyalCrest": "RoyalCrest", "EmeraldTarge": "EmeraldTarge", "CrimsonHeater": "CrimsonHeater",
            "CopperKiteShield": "CopperKiteShield", "SapphireSparkShield": "SapphireSparkShield",
            "HerosHeraldry": "HerosHeraldry", "GildedVisage": "GildedVisage", "MoltenAegis": "MoltenAegis",
            "LivingWoodDefender": "LivingWoodDefender", "BlueMoonCrest": "BlueMoonCrest",
            "CultistWard": "CultistWard", "PlatinumShield": "PlatinumShield", "HornetCarapace": "HornetCarapace",
            "PlagueBringerGuard": "PlagueBringerGuard", "VoidBarrier": "VoidBarrier",
            "HallowedAegis": "HallowedAegis", "CrimtaneTowerShield": "CrimtaneTowerShield",
            "VampireCountGuard": "VampireCountGuard", "ShadowScaleMailPiece": "ShadowScaleMailPiece",
            "CelestialCross": "CelestialCross", "MaskoftheSaints": "MaskoftheSaints",
            "SerratedScraper": "SerratedScraper", "RoughHewnCleaver": "RoughHewnCleaver", "PebblePounder": "PebblePounder",
            "WoodenPickaxe": "woodenpickaxe", "CopperPickaxe": "copperpickaxe", "IronPickaxe": "ironpickaxe",
            "SilverPickaxe": "silverpickaxe", "GoldPickaxe": "goldpickaxe", "TinPickaxe": "tinpickaxe",
            "LeadPickaxe": "leadpickaxe", "TungstenPickaxe": "tungstenpickaxe", "PlatinumPickaxe": "platinumpickaxe",
            "WoodenSword": "woodensword", "CopperSword": "coppersword", "IronSword": "ironsword",
            "SilverSword": "silversword", "GoldSword": "goldsword", "WoodenBow": "woodenbow",
            "CopperBow": "copperbow", "TinBow": "tinbow", "LeadBow": "leadbow", "IronBow": "ironbow",
            "SilverBow": "silverbow", "TungstenBow": "tungstenbow", "GoldBow": "goldbow",
            "PlatinumBow": "platinumbow", "TinSword": "tinsword", "LeadSword": "leadsword",
            "TungstenSword": "tungstensword", "PlatinumSword": "platinumsword",
            "CobaltTrident": "cobalt_trident", "WoodenWand": "woodenwand", "OnyxWand": "onyxwand",
            "MorganiteStaff": "morganitewand", "AmethystStaff": "AmethystStaff",
            "SpessartiteStaff": "spessartitegarnetstaff", "AquamarineStaff": "aquamarinestaff",
            "TopazStaff": "topazstaff", "SapphireStaff": "sapphirestaff", "EmeraldStaff": "emeraldstaff",
            "RubyStaff": "rubystaff",
            "CopperHelmet": "copperhelmet", "CopperChestplate": "copperchestplate", "CopperLeggings": "copperleggings",
            "IronHelmet": "ironhelmet", "IronChestplate": "ironchestplate", "IronLeggings": "ironleggings",
            "SilverHelmet": "silverhelmet", "SilverChestplate": "silverchestplate", "SilverLeggings": "silverleggings",
            "GoldHelmet": "goldhelmet", "GoldChestplate": "goldchestplate", "GoldLeggings": "goldleggings",
            "TinHelmet": "tinhelmet", "TinChestplate": "tinchestplate", "TinLeggings": "tinleggings",
            "LeadHelmet": "leadhelmet", "LeadChestplate": "leadchestplate", "LeadLeggings": "leadleggings",
            "TungstenHelmet": "tungstenhelmet", "TungstenChestplate": "tungstenchestplate", "TungstenLeggings": "tungstenleggings",
            "PlatinumHelmet": "platinumhelmet", "PlatinumChestplate": "platinumchestplate", "PlatinumLeggings": "platinumleggings",
            "AmberstoneHelmet": "amberstonehelmet", "AmberstoneChestplate": "amberstonechestplate", "AmberstoneLeggings": "amberstoneleggings",
            "NatureWings": "naturewings", "ThornwoodWings": "thornwoodwings",
            "Onion": "onion", "Garlic": "garlic", "Pumpkin": "pumpkin", "Carrot": "carrot",
            "Potato": "potato", "Tomato": "tomato", "Strawberry": "strawberry", "Corn": "corn", "Eggplant": "eggplant",
            "HealthPotionI": "HealthPotionI", "HealthPotionII": "healthpotionii", "HealthPotionIII": "healthpotioniii",
            "HealthPotionIV": "healthpotioniv", "HealthPotionV": "healthpotionv",
            "RegeneratePotionI": "regeneratepotioni", "RegeneratePotionII": "regeneratepotionii",
            "RegeneratePotionIII": "regeneratepotioniii", "RegeneratePotionIV": "regeneratepotioniv",
            "RegeneratePotionV": "regeneratepotionv", "SwiftnessPotionI": "swiftnesspotioni",
            "SwiftnessPotionII": "swiftnesspotionii", "ManaPotionI": "manapotioni", "ManaPotionII": "manapotionii",
            "ManaPotionIII": "manapotioniii", "ManaPotionIV": "manapotioniv", "ManaPotionV": "manapotionv",
            "StrengthPotion": "strengthpotion", "ResistancePotion": "resistancepotion",
            "Torch": "torch", "Chest": "chest", "GoldCoins": "goldcoin",
            "StarterKit": "StarterKit", "RookieKit": "RookieKit", "MinerKit": "MinerKit", "ScoutKit": "ScoutKit",
            "HunterKit": "HunterKit", "EliteKit": "EliteKit", "VeteranKit": "VeteranKit", "ShadowKit": "ShadowKit",
            "ConquerorKit": "ConquerorKit", "KingKit": "KingKit", "OverlordKit": "OverlordKit", "EternalKit": "EternalKit",
            "StarterVoucher": "StarterVoucher", "RookieVoucher": "RookieVoucher", "MinerVoucher": "MinerVoucher",
            "ScoutVoucher": "ScoutVoucher", "HunterVoucher": "HunterVoucher", "EliteVoucher": "EliteVoucher",
            "VeteranVoucher": "VeteranVoucher", "ShadowVoucher": "ShadowVoucher", "ConquerorVoucher": "ConquerorVoucher",
            "KingVoucher": "KingVoucher", "OverlordVoucher": "OverlordVoucher", "EternalVoucher": "EternalVoucher",
            "RookieCertificate": "RookieCertificate", "MinerCertificate": "MinerCertificate",
            "ScoutCertificate": "ScoutCertificate", "HunterCertificate": "HunterCertificate",
            "EliteCertificate": "EliteCertificate", "VeteranCertificate": "VeteranCertificate",
            "ShadowCertificate": "ShadowCertificate", "ConquerorCertificate": "ConquerorCertificate",
            "KingCertificate": "KingCertificate", "OverlordCertificate": "OverlordCertificate",
            "EternalCertificate": "EternalCertificate",
            "AdKey": "adKey", "RareKey": "RareKey", "MythicKey": "MythicKey", "DivineKey": "DivineKey",
        };

// A fallback-friendly iconUrl function
function iconUrl(itemID) {
    if (!itemID || itemID === 'None' || itemID === 'none') return null;
    const file = ICON_MAP[itemID] || itemID.toLowerCase();
    return 'assets/items/' + file + '.png';
}
